#!/usr/bin/env python
"""Auto-generate MicMute.spec with correct paths and version info.

Run this script whenever the project is moved or cloned to a new location,
or when preparing a new release build.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path


def get_version() -> str:
    """Get the current version from git tags.

    Uses git describe to get the version from the latest tag.
    Falls back to _version.py or unknown if git is not available.

    Returns:
        The version string.
    """
    import subprocess

    # Try to get version from git describe
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--long"],
            capture_output=True,
            text=True,
            cwd=Path(__file__).parent,
        )
        if result.returncode == 0:
            # Parse "v2.13.11-0-gabc1234" -> "2.13.11"
            describe = result.stdout.strip()
            if "-0-" in describe:
                # We're exactly on a tag
                version = describe.split("-")[0].lstrip("v")
                return version
            else:
                # We're ahead of a tag, use the tag part
                version = describe.split("-")[0].lstrip("v")
                return version
    except Exception:
        pass

    # Fallback to _version.py if it exists
    src_dir = Path(__file__).parent / "src"
    version_file = src_dir / "MicMute" / "_version.py"
    if version_file.exists():
        with open(version_file) as f:
            for line in f:
                if line.startswith("__version__"):
                    return line.split("=")[1].strip().strip('"\'')

    return "0.0.0+unknown"


def parse_version_info(version: str) -> tuple[int, int, int, int, str]:
    """Parse version string into Windows version info tuple.

    Args:
        version: Version string (e.g., "2.13.9" or "2.13.9.post1")

    Returns:
        Tuple of (major, minor, patch, build, suffix)
    """
    # Remove any 'v' prefix
    version = version.lstrip("v")

    # Split off any suffix (like +dev, .post1, etc.)
    if "+" in version:
        version, _ = version.split("+", 1)
    if ".post" in version:
        version, _ = version.split(".post", 1)
    if ".dev" in version:
        version, _ = version.split(".dev", 1)
    if "a" in version:
        version, _ = version.split("a", 1)
    if "b" in version:
        version, _ = version.split("b", 1)
    if "rc" in version:
        version, _ = version.split("rc", 1)

    parts = version.split(".")
    major = int(parts[0]) if len(parts) > 0 else 0
    minor = int(parts[1]) if len(parts) > 1 else 0
    patch = int(parts[2]) if len(parts) > 2 else 0
    build = int(parts[3]) if len(parts) > 3 else 0

    return (major, minor, patch, build, "")


def generate_spec() -> None:
    """Generate the PyInstaller spec file with version info."""
    # Get paths
    base_dir = Path(__file__).parent.resolve()
    src_dir = base_dir / "src"
    entry_point = base_dir / "run.py"
    assets_src = src_dir / "MicMute" / "assets"
    spec_file = base_dir / "MicMute.spec"

    # Validate paths
    if not entry_point.exists():
        print(f"ERROR: Entry point not found: {entry_point}")
        sys.exit(1)
    if not assets_src.exists():
        print(f"ERROR: Assets directory not found: {assets_src}")
        sys.exit(1)

    # Get version
    version = get_version()
    version_tuple = parse_version_info(version)

    print(f"Building MicMute v{version}")
    print(f"Version info: {version_tuple}")

    # Windows version info resource
    version_info = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by generate_spec.py - DO NOT EDIT MANUALLY
# Version: {version}

from PyInstaller.utils.win32.versioninfo import VSVersionInfo, FixedFileInfo, StringFileInfo, StringTable, StringStruct, VarFileInfo, VarStruct

import MicMute

a = Analysis(
    [r'{entry_point}'],
    pathex=[r'{src_dir}'],
    binaries=[],
    datas=[(r'{assets_src}', 'MicMute/assets')],
    hiddenimports=[
        'PySide6',
        'comtypes',
        'pycaw',
        'winsound',
        'MicMute._version',
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

# Windows version info
vs_info = VSVersionInfo(
    ffi=FixedFileInfo(
        filevers={version_tuple[:4]},
        prodvers={version_tuple[:4]},
        mask=0x3f,
        flags=0x0,
        OS=0x40004,
        fileType=0x1,
        subtype=0x0,
        date=(0, 0)
    ),
    kids=[
        StringFileInfo(
            [
                StringTable(
                    '040904B0',
                    [
                        StringStruct('CompanyName', 'madbeat14'),
                        StringStruct('FileDescription', 'MicMute - Microphone Mute Toggle'),
                        StringStruct('FileVersion', '{version}'),
                        StringStruct('InternalName', 'MicMute'),
                        StringStruct('LegalCopyright', 'Copyright (c) 2024 madbeat14'),
                        StringStruct('OriginalFilename', 'MicMute.exe'),
                        StringStruct('ProductName', 'MicMute'),
                        StringStruct('ProductVersion', '{version}'),
                    ]
                )
            ]
        ),
        VarFileInfo([VarStruct('Translation', [1033, 1200])])
    ]
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='MicMute',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version=vs_info,
)
"""

    # Write spec file
    with open(spec_file, "w", encoding="utf-8") as f:
        f.write(version_info)

    print(f"[OK] Generated {spec_file}")
    print(f"  Entry point: {entry_point}")
    print(f"  Source path: {src_dir}")
    print(f"  Assets: {assets_src}")
    print(f"  Version: {version}")


if __name__ == "__main__":
    generate_spec()
