#!/usr/bin/env python
"""
Auto-generate MicMute.spec with correct paths for the current environment.
Run this script whenever the project is moved or cloned to a new location.
"""
import os

# Get the directory where this script is located
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(BASE_DIR, 'src')
ENTRY_POINT = os.path.join(BASE_DIR, 'run.py')
ASSETS_SRC = os.path.join(SRC_DIR, 'MicMute', 'assets')
SPEC_FILE = os.path.join(BASE_DIR, 'MicMute.spec')

# Validate paths exist
if not os.path.exists(ENTRY_POINT):
    print(f"ERROR: Entry point not found: {ENTRY_POINT}")
    exit(1)
if not os.path.exists(ASSETS_SRC):
    print(f"ERROR: Assets directory not found: {ASSETS_SRC}")
    exit(1)

# Generate spec file content
SPEC_CONTENT = f'''# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by generate_spec.py - DO NOT EDIT MANUALLY

a = Analysis(
    [r'{ENTRY_POINT}'],
    pathex=[r'{SRC_DIR}'],
    binaries=[],
    datas=[(r'{ASSETS_SRC}', 'MicMute\\\\assets')],
    hiddenimports=['PySide6', 'comtypes', 'pycaw', 'winsound'],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='MicMute',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
'''

# Write spec file
with open(SPEC_FILE, 'w') as f:
    f.write(SPEC_CONTENT)

print(f"✓ Generated {SPEC_FILE}")
print(f"  Entry point: {ENTRY_POINT}")
print(f"  Source path: {SRC_DIR}")
print(f"  Assets: {ASSETS_SRC}")
